version: "3"
services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && yarn install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "5000:3000"
    environment:
      NODE_ENV: production
      RAILS_ENV: production
    depends_on:
      - db
volumes:
  db_data:
